# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-10 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone as dut


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('avg_speed', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('place_id', models.CharField(max_length=100)),
                ('record_time', models.DateField(default=dut.now)),
            ],
        ),
    ]
